### ISSUE TITLE
Newlines within paragraph

### ISSUE THREAD

**Issue by andrew-sumner** [concordion/concordion-markdown-extension#5]
In my first attempt at using this extension I formatted my example as follows

```
## [View successful log out message](- "example1")
Given I am currently logged in 
When [I logout](- "logOutClient()")
Then I can see the successful logout message [You have logged out.](- "c:assertEquals=getLogOutMessage()")
And I [cannot see the client number](- "c:assertFalse=isClientNumberVisible()")
```

but found that the newlines were getting ignored and I had one long paragraph in the generated specification.  The very unintuitive workaround is to place two spaces at the end of each line. GitHub have very sensibly made the decision to obey the newline without the need for two spaces at the end of the line, other wiki editors don't.  

Should this extension also follow the github standard?

**Comment by andrew-sumner** [comment]
After converting several specifications and using the default markdown editor in Eclipse it's probably not worth doing anything about this as it's so easy to see formatting issues. 

This is an awesome extension!

**Comment by nigelcharman** [comment]
I think this is a valid concern. 

It looks like you can implement Github Flavoured Markdown style newlines by [configuring](http://concordion.github.io/concordion-markdown-extension/spec/concordion/markdown/Configuration.html) the extension to use Markdown syntax extensions. The Pegdown [HARDWRAPS](https://github.com/sirthias/pegdown/blob/master/README.markdown) extension should do what you want. 

I'll reopen this issue, since I think we should at least document this. Please update this issue if you get a chance to test it with HARDWRAPS and whether it resolves your original issue.
